services:
  node-installer:
    image: node:24-alpine
    working_dir: /home/node/project
    volumes:
      - .:/home/node/project
    command: npm i

  app:
    image: node:24-alpine
    working_dir: /home/node/project
    volumes:
      - .:/home/node/project
    command: npm run dev:mongo
    depends_on:
      mongo:
        condition: service_started
      node-installer:
        condition: service_completed_successfully
    environment:
      MONGO_URL: mongodb://root:password@mongo:27017/marketplace?authSource=admin

  mongo:
    image: mongo:8.0-noble
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: marketplace
    volumes:
      - mongo_data:/data/db
      - ./database/mongo:/docker-entrypoint-initdb.d:ro

volumes:
  mongo_data: